// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaraguyAPI.Models;

#nullable disable

namespace TaraguyAPI.Migrations
{
    [DbContext(typeof(TaraguyDbContext))]
    [Migration("20251229184651_TablasOrdenes")]
    partial class TablasOrdenes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaraguyAPI.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("categorias_pkey");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.DetalleOrden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_producto");

                    b.Property<int>("OrdenId")
                        .HasColumnType("integer")
                        .HasColumnName("orden_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.HasKey("Id")
                        .HasName("detalle_ordenes_pkey");

                    b.HasIndex("OrdenId");

                    b.ToTable("detalle_ordenes", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int?>("VentaId")
                        .HasColumnType("integer")
                        .HasColumnName("venta_id");

                    b.HasKey("Id")
                        .HasName("detalle_ventas_pkey");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("detalle_ventas", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.Noticia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Copete")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("copete");

                    b.Property<string>("Cuerpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cuerpo");

                    b.Property<bool?>("EsDestacada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_destacada");

                    b.Property<DateTime?>("FechaPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_publicacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("noticias_pkey");

                    b.HasIndex("CategoriaId");

                    b.ToTable("noticias", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.Orden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido_cliente");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .HasColumnType("text")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("CodigoSeguimiento")
                        .HasColumnType("text")
                        .HasColumnName("codigo_seguimiento");

                    b.Property<string>("DireccionCalle")
                        .HasColumnType("text")
                        .HasColumnName("direccion_calle");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MercadoPagoId")
                        .HasColumnType("text")
                        .HasColumnName("mercado_pago_id");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_cliente");

                    b.Property<string>("Provincia")
                        .HasColumnType("text")
                        .HasColumnName("provincia");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoEnvio")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_envio");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("ordenes_pkey");

                    b.ToTable("ordenes", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cancha")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cancha");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disciplina")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("disciplina");

                    b.Property<bool?>("EsLocal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("es_local");

                    b.Property<string>("EscudoRivalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("escudo_rival_url");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("Resultado")
                        .HasColumnType("text");

                    b.Property<string>("Rival")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rival");

                    b.Property<string>("Torneo")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("partidos_pkey");

                    b.ToTable("partidos", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("CategoriaProducto")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("categoria_producto")
                        .HasDefaultValueSql("'Indumentaria'::character varying");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("productos_pkey");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.Sponsor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("LinkWeb")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link_web");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("Orden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("sponsors_pkey");

                    b.ToTable("sponsors", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol")
                        .HasDefaultValueSql("'admin'::character varying");

                    b.HasKey("Id")
                        .HasName("usuarios_pkey");

                    b.HasIndex(new[] { "NombreUsuario" }, "usuarios_nombre_usuario_key")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Pendiente'::character varying");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("IdTransaccionMp")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id_transaccion_mp");

                    b.Property<string>("NombreComprador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_comprador");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono_contacto");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.HasKey("Id")
                        .HasName("ventas_pkey");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("TaraguyAPI.Models.DetalleOrden", b =>
                {
                    b.HasOne("TaraguyAPI.Models.Orden", "Orden")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("detalle_ordenes_orden_id_fkey");

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("TaraguyAPI.Models.DetalleVenta", b =>
                {
                    b.HasOne("TaraguyAPI.Models.Producto", "Producto")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("detalle_ventas_producto_id_fkey");

                    b.HasOne("TaraguyAPI.Models.Venta", "Venta")
                        .WithMany("DetalleVenta")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("detalle_ventas_venta_id_fkey");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("TaraguyAPI.Models.Noticia", b =>
                {
                    b.HasOne("TaraguyAPI.Models.Categoria", "Categoria")
                        .WithMany("Noticia")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("noticias_categoria_id_fkey");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("TaraguyAPI.Models.Categoria", b =>
                {
                    b.Navigation("Noticia");
                });

            modelBuilder.Entity("TaraguyAPI.Models.Orden", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("TaraguyAPI.Models.Producto", b =>
                {
                    b.Navigation("DetalleVenta");
                });

            modelBuilder.Entity("TaraguyAPI.Models.Venta", b =>
                {
                    b.Navigation("DetalleVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
